function(){return function(){var n,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ca(a,b){if(b){for(var c=ba,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&aa(c,d,{configurable:!0,writable:!0,value:f})}}
ca("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});ca("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var p=this;function da(a){return void 0!==a}
function ea(a,b){var c=a.split("."),d=p;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&da(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function fa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"string"==typeof a}function ga(a){return"number"==typeof a}function ha(a){return"function"==fa(a)}function ia(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ja(a,b,c){return a.call.apply(a.bind,arguments)}
function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function la(a,b,c){la=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return la.apply(null,arguments)}
function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var oa=Date.now||function(){return+new Date};function r(a,b){function c(){}c.prototype=b.prototype;a.Ka=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Aa=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var pa=window;function qa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,qa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(qa,Error);qa.prototype.name="CustomError";var ra;function sa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var ta=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function ua(a,b){for(var c=0,d=ta(String(a)).split("."),e=ta(String(b)).split("."),f=Math.max(d.length,e.length),g=0;!c&&g<f;g++){var h=d[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var A=m.exec(h)||["","",""],K=k.exec(l)||["","",""];if(0==A[0].length&&0==K[0].length)break;c=va(0==A[1].length?0:parseInt(A[1],10),0==K[1].length?0:parseInt(K[1],10))||va(0==A[2].length,0==K[2].length)||va(A[2],K[2])}while(!c)}return c}function va(a,b){return a<b?-1:a>b?1:0}
function wa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function xa(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function t(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function ya(a,b){for(var c=a.length,d=[],e=0,f=q(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}
function za(a,b){for(var c=a.length,d=Array(c),e=q(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function Aa(a,b,c){var d=c;t(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function Ba(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Ca(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function Da(a,b){var c;a:{c=a.length;for(var d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:q(a)?a.charAt(c):a[c]}function Ea(a){return Array.prototype.concat.apply(Array.prototype,arguments)}function Fa(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Ga={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Ha="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ia=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ja=/^#(?:[0-9a-f]{3}){1,2}$/i,Ka=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,La=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function u(a,b){this.code=a;this.a=v[a]||Ma;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}r(u,Error);var Ma="unknown error",v={15:"element not selectable",11:"element not visible"};v[31]=Ma;v[30]=Ma;v[24]="invalid cookie domain";v[29]="invalid element coordinates";v[12]="invalid element state";
v[32]="invalid selector";v[51]="invalid selector";v[52]="invalid selector";v[17]="javascript error";v[405]="unsupported operation";v[34]="move target out of bounds";v[27]="no such alert";v[7]="no such element";v[8]="no such frame";v[23]="no such window";v[28]="script timeout";v[33]="session not created";v[10]="stale element reference";v[21]="timeout";v[25]="unable to set cookie";v[26]="unexpected alert open";v[13]=Ma;v[9]="unknown command";u.prototype.toString=function(){return this.name+": "+this.message};var Oa;a:{var Pa=p.navigator;if(Pa){var Qa=Pa.userAgent;if(Qa){Oa=Qa;break a}}Oa=""}function w(a){return-1!=Oa.indexOf(a)};function Ra(){return w("Opera")||w("OPR")}function Sa(){return(w("Chrome")||w("CriOS"))&&!Ra()&&!w("Edge")};function Ta(){return w("iPhone")&&!w("iPod")&&!w("iPad")};var Ua=Ra(),x=w("Trident")||w("MSIE"),Va=w("Edge"),y=w("Gecko")&&!(-1!=Oa.toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),Wa=-1!=Oa.toLowerCase().indexOf("webkit")&&!w("Edge");function Xa(){var a=Oa;if(y)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Va)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Wa)return/WebKit\/(\S+)/.exec(a)}function Ya(){var a=p.document;return a?a.documentMode:void 0}
var Za=function(){if(Ua&&p.opera){var a;var b=p.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Xa())&&(a=b?b[1]:"");return x&&(b=Ya(),null!=b&&b>parseFloat(a))?String(b):a}(),$a={};function ab(a){return $a[a]||($a[a]=0<=ua(Za,a))}var bb=p.document,cb=bb&&x?Ya()||("CSS1Compat"==bb.compatMode?parseInt(Za,10):5):void 0;var db=w("Firefox"),eb=Ta()||w("iPod"),fb=w("iPad"),gb=w("Android")&&!(Sa()||w("Firefox")||Ra()||w("Silk")),hb=Sa(),ib=w("Safari")&&!(Sa()||w("Coast")||Ra()||w("Edge")||w("Silk")||w("Android"))&&!(Ta()||w("iPad")||w("iPod"));function jb(a){return(a=a.exec(Oa))?a[1]:""}var kb=function(){if(db)return jb(/Firefox\/([0-9.]+)/);if(x||Va||Ua)return Za;if(hb)return jb(/Chrome\/([0-9.]+)/);if(ib&&!(Ta()||w("iPad")||w("iPod")))return jb(/Version\/([0-9.]+)/);if(eb||fb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Oa);if(a)return a[1]+"."+a[2]}else if(gb)return(a=jb(/Android\s+([0-9.]+)/))?a:jb(/Version\/([0-9.]+)/);return""}();var lb={},mb,nb;function ob(a){return pb?mb(a):x?0<=ua(cb,a):ab(a)}function qb(a){return pb?nb(a):gb?0<=ua(rb,a):0<=ua(kb,a)}
var pb=function(){if(!y)return!1;var a=p.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;mb=function(a){return 0<=c.compare(d,""+a)};nb=function(a){return 0<=c.compare(e,""+a)};return!0}(),sb=fb||eb,tb;
if(gb){var ub=/Android\s+([0-9\.]+)/.exec(Oa);tb=ub?ub[1]:"0"}else tb="0";var rb=tb,vb=x&&!(8<=Number(cb)),wb=x&&!(9<=Number(cb));gb&&qb(2.3);gb&&qb(4);ib&&qb(6);!y&&!x||x&&9<=Number(cb)||y&&ab("1.9.1");x&&ab("9");function xb(a,b){this.x=da(a)?a:0;this.y=da(b)?b:0}n=xb.prototype;n.clone=function(){return new xb(this.x,this.y)};n.toString=function(){return"("+this.x+", "+this.y+")"};n.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};n.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};n.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};n.scale=function(a,b){var c=ga(b)?b:a;this.x*=a;this.y*=c;return this};function yb(a,b){this.width=a;this.height=b}n=yb.prototype;n.clone=function(){return new yb(this.width,this.height)};n.toString=function(){return"("+this.width+" x "+this.height+")"};n.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};n.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};n.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
n.scale=function(a,b){var c=ga(b)?b:a;this.width*=a;this.height*=c;return this};function z(a){return a?new zb(B(a)):ra||(ra=new zb)}
function Ab(a,b,c,d){a=d||a;var e=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;g=b[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=xa(e.split(/\s+/),c);h&&(a[d++]=g)}a.length=d;return a}return b}
function Bb(a){return a.scrollingElement?a.scrollingElement:Wa||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Cb(a){return a?a.parentWindow||a.defaultView:window}function Db(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function Eb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Fb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(x&&!(9<=Number(cb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Gb(a,b):!c&&Eb(e,b)?-1*Hb(a,b):!d&&Eb(f,a)?Hb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=B(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(p.Range.START_TO_END,d)}function Hb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return Gb(d,a)}function Gb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function B(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var Ib={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Jb={IMG:" ",BR:"\n"};
function Kb(a,b,c){if(!(a.nodeName in Ib))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Jb)b.push(Jb[a.nodeName]);else for(a=a.firstChild;a;)Kb(a,b,c),a=a.nextSibling}function Lb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function zb(a){this.a=a||p.document||document}function Mb(a,b,c,d){return Ab(a.a,b,c,d)};function Nb(a,b){b=b.toLowerCase();if("style"==b)return Ob(a.style.cssText);if(vb&&"value"==b&&C(a,"INPUT"))return a.value;if(wb&&!0===a[b])return String(a.getAttribute(b));var c=a.getAttributeNode(b);return c&&c.specified?c.value:null}var Pb=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function Ob(a){var b=[];t(a.split(Pb),function(a){var d=a.indexOf(":");0<d&&(a=[a.slice(0,d),a.slice(d+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function Qb(a,b){var c;vb&&"value"==b&&C(a,"OPTION")&&null===Nb(a,"value")?(c=[],Kb(a,c,!1),c=c.join("")):c=a[b];return c}function C(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function Rb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var Sb=x&&!(9<=Number(cb)),Tb=x&&!(8<=Number(cb));function Ub(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Vb(a,b){var c=Tb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Ub(b,a,b.nodeName,c)};function Wb(a){this.b=a;this.a=0}function Xb(a){a=a.match(Yb);for(var b=0;b<a.length;b++)Zb.test(a[b])&&a.splice(b,1);return new Wb(a)}var Yb=RegExp("\\$?(?:(?![0-9-\\.])(?:\\*|[\\w-\\.]+):)?(?![0-9-\\.])(?:\\*|[\\w-\\.]+)|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Zb=/^\s/;function D(a,b){return a.b[a.a+(b||0)]}function E(a){return a.b[a.a++]}function $b(a){return a.b.length<=a.a};function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(Sb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),Sb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function ac(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Tb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function bc(a,b,c,d,e){return(Sb?cc:dc).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new G)}
function cc(a,b,c,d,e){if(a instanceof ec||8==a.g||c&&null===a.g){var f=b.all;if(!f)return e;a=fc(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],h=0;b=f[h++];)ac(b,c,d)&&g.push(b);f=g}for(h=0;b=f[h++];)"*"==a&&"!"==b.tagName||H(e,b);return e}gc(a,b,c,d,e);return e}
function dc(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!x?(b=b.getElementsByName(d),t(b,function(b){a.a(b)&&H(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),t(b,function(b){b.className==d&&a.a(b)&&H(e,b)})):a instanceof I?gc(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.b()),t(b,function(a){ac(a,c,d)&&H(e,a)}));return e}
function hc(a,b,c,d,e){var f;if((a instanceof ec||8==a.g||c&&null===a.g)&&(f=b.childNodes)){var g=fc(a);if("*"!=g&&(f=ya(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=ya(f,function(a){return ac(a,c,d)}));t(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||H(e,a)});return e}return ic(a,b,c,d,e)}function ic(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)ac(b,c,d)&&a.a(b)&&H(e,b);return e}
function gc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)ac(b,c,d)&&a.a(b)&&H(e,b),gc(a,b,c,d,e)}function fc(a){if(a instanceof I){if(8==a.g)return"!";if(null===a.g)return"*"}return a.b()};function G(){this.b=this.a=null;this.m=0}function jc(a){this.node=a;this.a=this.b=null}function kc(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f,g=0;c&&d;){f=c.node;var h=d.node;f==h||f instanceof Ub&&h instanceof Ub&&f.a==h.a?(f=c,c=c.a,d=d.a):0<Fb(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.m=g;return a}G.prototype.unshift=function(a){a=new jc(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.m++};
function H(a,b){var c=new jc(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.m++}function lc(a){return(a=a.a)?a.node:null}G.prototype.f=function(){var a=lc(this);return a?F(a):""};function mc(a,b){return new nc(a,!!b)}function nc(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function J(a){var b=a.b;if(b){var c=a.a=b;a.b=a.c?b.b:b.a;return c.node}return null};function L(a){this.l=a;this.b=this.h=!1;this.f=null}function M(a){return"\n  "+a.toString().split("\n").join("\n  ")}function oc(a,b){a.h=b}function pc(a,b){a.b=b}function N(a,b){var c=a.a(b);return c instanceof G?+c.f():+c}function O(a,b){var c=a.a(b);return c instanceof G?c.f():""+c}function qc(a,b){var c=a.a(b);return c instanceof G?!!c.m:!!c};function rc(a,b,c){L.call(this,a.l);this.c=a;this.i=b;this.v=c;this.h=b.h||c.h;this.b=b.b||c.b;this.c==sc&&(c.b||c.h||4==c.l||0==c.l||!b.f?b.b||b.h||4==b.l||0==b.l||!c.f||(this.f={name:c.f.name,w:b}):this.f={name:b.f.name,w:c})}r(rc,L);
function tc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof G&&c instanceof G){b=mc(b);for(d=J(b);d;d=J(b))for(e=mc(c),f=J(e);f;f=J(e))if(a(F(d),F(f)))return!0;return!1}if(b instanceof G||c instanceof G){b instanceof G?(e=b,d=c):(e=c,d=b);f=mc(e);for(var g=typeof d,h=J(f);h;h=J(f)){switch(g){case "number":h=+F(h);break;case "boolean":h=!!F(h);break;case "string":h=F(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}rc.prototype.a=function(a){return this.c.o(this.i,this.v,a)};rc.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+M(this.i);return a+=M(this.v)};function uc(a,b,c,d){this.a=a;this.M=b;this.l=c;this.o=d}uc.prototype.toString=function(){return this.a};var vc={};
function P(a,b,c,d){if(vc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new uc(a,b,c,d);return vc[a.toString()]=a}P("div",6,1,function(a,b,c){return N(a,c)/N(b,c)});P("mod",6,1,function(a,b,c){return N(a,c)%N(b,c)});P("*",6,1,function(a,b,c){return N(a,c)*N(b,c)});P("+",5,1,function(a,b,c){return N(a,c)+N(b,c)});P("-",5,1,function(a,b,c){return N(a,c)-N(b,c)});P("<",4,2,function(a,b,c){return tc(function(a,b){return a<b},a,b,c)});
P(">",4,2,function(a,b,c){return tc(function(a,b){return a>b},a,b,c)});P("<=",4,2,function(a,b,c){return tc(function(a,b){return a<=b},a,b,c)});P(">=",4,2,function(a,b,c){return tc(function(a,b){return a>=b},a,b,c)});var sc=P("=",3,2,function(a,b,c){return tc(function(a,b){return a==b},a,b,c,!0)});P("!=",3,2,function(a,b,c){return tc(function(a,b){return a!=b},a,b,c,!0)});P("and",2,2,function(a,b,c){return qc(a,c)&&qc(b,c)});P("or",1,2,function(a,b,c){return qc(a,c)||qc(b,c)});function wc(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");L.call(this,a.l);this.c=a;this.i=b;this.h=a.h;this.b=a.b}r(wc,L);wc.prototype.a=function(a){a=this.c.a(a);return xc(this.i,a)};wc.prototype.toString=function(){var a;a="Filter:"+M(this.c);return a+=M(this.i)};function yc(a,b){if(b.length<a.L)throw Error("Function "+a.j+" expects at least"+a.L+" arguments, "+b.length+" given");if(null!==a.C&&b.length>a.C)throw Error("Function "+a.j+" expects at most "+a.C+" arguments, "+b.length+" given");a.Y&&t(b,function(b,d){if(4!=b.l)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});L.call(this,a.l);this.i=a;this.c=b;oc(this,a.h||Ba(b,function(a){return a.h}));pc(this,a.X&&!b.length||a.V&&!!b.length||Ba(b,function(a){return a.b}))}
r(yc,L);yc.prototype.a=function(a){return this.i.o.apply(null,Ea(a,this.c))};yc.prototype.toString=function(){var a="Function: "+this.i;if(this.c.length)var b=Aa(this.c,function(a,b){return a+M(b)},"Arguments:"),a=a+M(b);return a};function zc(a,b,c,d,e,f,g,h,l){this.j=a;this.l=b;this.h=c;this.X=d;this.V=e;this.o=f;this.L=g;this.C=da(h)?h:g;this.Y=!!l}zc.prototype.toString=function(){return this.j};var Ac={};
function Q(a,b,c,d,e,f,g,h){if(Ac.hasOwnProperty(a))throw Error("Function already created: "+a+".");Ac[a]=new zc(a,b,c,d,!1,e,f,g,h)}Q("boolean",2,!1,!1,function(a,b){return qc(b,a)},1);Q("ceiling",1,!1,!1,function(a,b){return Math.ceil(N(b,a))},1);Q("concat",3,!1,!1,function(a,b){return Aa(Fa(arguments,1),function(b,d){return b+O(d,a)},"")},2,null);Q("contains",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return-1!=b.indexOf(a)},2);Q("count",1,!1,!1,function(a,b){return b.a(a).m},1,1,!0);
Q("false",2,!1,!1,function(){return!1},0);Q("floor",1,!1,!1,function(a,b){return Math.floor(N(b,a))},1);Q("id",4,!1,!1,function(a,b){function c(a){if(Sb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Da(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=O(b,a).split(/\s+/),f=[];t(d,function(a){a=c(a);!a||0<=xa(f,a)||f.push(a)});f.sort(Fb);var g=new G;t(f,function(a){H(g,a)});return g},1);
Q("lang",2,!1,!1,function(){return!1},1);Q("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);Q("local-name",3,!1,!0,function(a,b){var c=b?lc(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);Q("name",3,!1,!0,function(a,b){var c=b?lc(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);Q("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
Q("normalize-space",3,!1,!0,function(a,b){return(b?O(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);Q("not",2,!1,!1,function(a,b){return!qc(b,a)},1);Q("number",1,!1,!0,function(a,b){return b?N(b,a):+F(a.a)},0,1);Q("position",1,!0,!1,function(a){return a.b},0);Q("round",1,!1,!1,function(a,b){return Math.round(N(b,a))},1);Q("starts-with",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return!b.lastIndexOf(a,0)},2);Q("string",3,!1,!0,function(a,b){return b?O(b,a):F(a.a)},0,1);
Q("string-length",1,!1,!0,function(a,b){return(b?O(b,a):F(a.a)).length},0,1);Q("substring",3,!1,!1,function(a,b,c,d){c=N(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?N(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=O(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);Q("substring-after",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
Q("substring-before",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);Q("sum",1,!1,!1,function(a,b){for(var c=mc(b.a(a)),d=0,e=J(c);e;e=J(c))d+=+F(e);return d},1,1,!0);Q("translate",3,!1,!1,function(a,b,c,d){b=O(b,a);c=O(c,a);var e=O(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);Q("true",2,!1,!1,function(){return!0},0);function I(a,b){this.c=a;this.f=da(b)?b:null;this.g=null;switch(a){case "comment":this.g=8;break;case "text":this.g=3;break;case "processing-instruction":this.g=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Bc(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}I.prototype.a=function(a){return null===this.g||this.g==a.nodeType};I.prototype.b=function(){return this.c};
I.prototype.toString=function(){var a="Kind Test: "+this.c;!this.f||(a+=M(this.f));return a};function Cc(a){L.call(this,3);this.c=a.substring(1,a.length-1)}r(Cc,L);Cc.prototype.a=function(){return this.c};Cc.prototype.toString=function(){return"Literal: "+this.c};function ec(a,b){this.j=a.toLowerCase();var c;c="*"==this.j?"*":"http://www.w3.org/1999/xhtml";this.f=b?b.toLowerCase():c}ec.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=da(a.localName)?a.localName:a.nodeName;return"*"!=this.j&&this.j!=b.toLowerCase()?!1:"*"==this.f?!0:this.f==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};ec.prototype.b=function(){return this.j};
ec.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.f?"":this.f+":")+this.j};function Dc(a){L.call(this,1);this.c=a}r(Dc,L);Dc.prototype.a=function(){return this.c};Dc.prototype.toString=function(){return"Number: "+this.c};function Ec(a,b){L.call(this,a.l);this.i=a;this.c=b;this.h=a.h;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.B||c.c!=Fc||(c=c.v,"*"!=c.b()&&(this.f={name:c.b(),w:null}))}}r(Ec,L);function Gc(){L.call(this,4)}r(Gc,L);Gc.prototype.a=function(a){var b=new G;a=a.a;9==a.nodeType?H(b,a):H(b,a.ownerDocument);return b};Gc.prototype.toString=function(){return"Root Helper Expression"};function Hc(){L.call(this,4)}r(Hc,L);Hc.prototype.a=function(a){var b=new G;H(b,a.a);return b};Hc.prototype.toString=function(){return"Context Helper Expression"};
function Ic(a){return"/"==a||"//"==a}Ec.prototype.a=function(a){var b=this.i.a(a);if(!(b instanceof G))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.m;c++){var e=a[c],f=mc(b,e.c.a),g;if(e.h||e.c!=Jc)if(e.h||e.c!=Kc)for(g=J(f),b=e.a(new Rb(g));g=J(f);)g=e.a(new Rb(g)),b=kc(b,g);else g=J(f),b=e.a(new Rb(g));else{for(g=J(f);(b=J(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new Rb(g))}}return b};
Ec.prototype.toString=function(){var a;a="Path Expression:"+M(this.i);if(this.c.length){var b=Aa(this.c,function(a,b){return a+M(b)},"Steps:");a+=M(b)}return a};function Lc(a,b){this.a=a;this.b=!!b}
function xc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=mc(b),f=b.m,g,h=0;g=J(e);h++){var l=a.b?f-h:h+1;g=d.a(new Rb(g,l,f));if("number"==typeof g)l=l==g;else if("string"==typeof g||"boolean"==typeof g)l=!!g;else if(g instanceof G)l=0<g.m;else throw Error("Predicate.evaluate returned an unexpected type.");if(!l){l=e;g=l.f;var m=l.a;if(!m)throw Error("Next must be called at least once before remove.");var k=m.b,m=m.a;k?k.a=m:g.a=m;m?m.b=k:g.b=k;g.m--;l.a=null}}return b}
Lc.prototype.toString=function(){return Aa(this.a,function(a,b){return a+M(b)},"Predicates:")};function Mc(a,b,c,d){L.call(this,4);this.c=a;this.v=b;this.i=c||new Lc([]);this.B=!!d;b=this.i;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=Sb?a.toLowerCase():a,this.f={name:a,w:b.w});a:{a=this.i;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.h||1==c.l||0==c.l){a=!0;break a}a=!1}this.h=a}r(Mc,L);
Mc.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.w?O(c.w,a):null,f=1);if(this.B)if(this.h||this.c!=Nc)if(b=mc((new Mc(Oc,new I("node"))).a(a)),c=J(b))for(a=this.o(c,d,e,f);c=J(b);)a=kc(a,this.o(c,d,e,f));else a=new G;else a=bc(this.v,b,d,e),a=xc(this.i,a,f);else a=this.o(a.a,d,e,f);return a};Mc.prototype.o=function(a,b,c,d){a=this.c.f(this.v,a,b,c);return a=xc(this.i,a,d)};
Mc.prototype.toString=function(){var a;a="Step:"+M("Operator: "+(this.B?"//":"/"));this.c.j&&(a+=M("Axis: "+this.c));a+=M(this.v);if(this.i.a.length){var b=Aa(this.i.a,function(a,b){return a+M(b)},"Predicates:");a+=M(b)}return a};function Pc(a,b,c,d){this.j=a;this.f=b;this.a=c;this.b=d}Pc.prototype.toString=function(){return this.j};var Qc={};function R(a,b,c,d){if(Qc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new Pc(a,b,c,!!d);return Qc[a]=b}
R("ancestor",function(a,b){for(var c=new G,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);R("ancestor-or-self",function(a,b){var c=new G,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var Fc=R("attribute",function(a,b){var c=new G,d=a.b();if("style"==d&&Sb&&b.style)return H(c,new Ub(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof I&&null===a.g||"*"==d)for(var d=0,f;f=e[d];d++)Sb?f.nodeValue&&H(c,Vb(b,f)):H(c,f);else(f=e.getNamedItem(d))&&(Sb?f.nodeValue&&H(c,Vb(b,f)):H(c,f));return c},!1),Nc=R("child",function(a,b,c,d,e){return(Sb?hc:ic).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new G)},!1,!0);R("descendant",bc,!1,!0);
var Oc=R("descendant-or-self",function(a,b,c,d){var e=new G;ac(b,c,d)&&a.a(b)&&H(e,b);return bc(a,b,c,d,e)},!1,!0),Jc=R("following",function(a,b,c,d){var e=new G;do for(var f=b;f=f.nextSibling;)ac(f,c,d)&&a.a(f)&&H(e,f),e=bc(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);R("following-sibling",function(a,b){for(var c=new G,d=b;d=d.nextSibling;)a.a(d)&&H(c,d);return c},!1);R("namespace",function(){return new G},!1);
var Rc=R("parent",function(a,b){var c=new G;if(9==b.nodeType)return c;if(2==b.nodeType)return H(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&H(c,d);return c},!1),Kc=R("preceding",function(a,b,c,d){var e=new G,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var l=[];for(b=f[g];b=b.previousSibling;)l.unshift(b);for(var m=0,k=l.length;m<k;m++)b=l[m],ac(b,c,d)&&a.a(b)&&H(e,b),e=bc(a,b,c,d,e)}return e},!0,!0);
R("preceding-sibling",function(a,b){for(var c=new G,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var Sc=R("self",function(a,b){var c=new G;a.a(b)&&H(c,b);return c},!1);function Tc(a){L.call(this,1);this.c=a;this.h=a.h;this.b=a.b}r(Tc,L);Tc.prototype.a=function(a){return-N(this.c,a)};Tc.prototype.toString=function(){return"Unary Expression: -"+M(this.c)};function Uc(a){L.call(this,4);this.c=a;oc(this,Ba(this.c,function(a){return a.h}));pc(this,Ba(this.c,function(a){return a.b}))}r(Uc,L);Uc.prototype.a=function(a){var b=new G;t(this.c,function(c){c=c.a(a);if(!(c instanceof G))throw Error("Path expression must evaluate to NodeSet.");b=kc(b,c)});return b};Uc.prototype.toString=function(){return Aa(this.c,function(a,b){return a+M(b)},"Union Expression:")};function Vc(a,b){this.a=a;this.b=b}function Wc(a){for(var b,c=[];;){S(a,"Missing right hand side of binary expression.");b=Xc(a);var d=E(a.a);if(!d)break;var e=(d=vc[d]||null)&&d.M;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].M;)b=new rc(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new rc(c.pop(),c.pop(),b);return b}function S(a,b){if($b(a.a))throw Error(b);}function Yc(a,b){var c=E(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Zc(a){a=E(a.a);if(")"!=a)throw Error("Bad token: "+a);}function $c(a){a=E(a.a);if(2>a.length)throw Error("Unclosed literal string");return new Cc(a)}
function ad(a){var b,c=[],d;if(Ic(D(a.a))){b=E(a.a);d=D(a.a);if("/"==b&&($b(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Gc;d=new Gc;S(a,"Missing next location step.");b=bd(a,b);c.push(b)}else{a:{b=D(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":E(a.a);b=Wc(a);S(a,'unclosed "("');Yc(a,")");break;case '"':case "'":b=$c(a);break;default:if(isNaN(+b))if(!Bc(b)&&/(?![0-9])[\w]/.test(d)&&"("==D(a.a,1)){b=E(a.a);
b=Ac[b]||null;E(a.a);for(d=[];")"!=D(a.a);){S(a,"Missing function argument list.");d.push(Wc(a));if(","!=D(a.a))break;E(a.a)}S(a,"Unclosed function argument list.");Zc(a);b=new yc(b,d)}else{b=null;break a}else b=new Dc(+E(a.a))}"["==D(a.a)&&(d=new Lc(cd(a)),b=new wc(b,d))}if(b)if(Ic(D(a.a)))d=b;else return b;else b=bd(a,"/"),d=new Hc,c.push(b)}for(;Ic(D(a.a));)b=E(a.a),S(a,"Missing next location step."),b=bd(a,b),c.push(b);return new Ec(d,c)}
function bd(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==D(a.a))return d=new Mc(Sc,new I("node")),E(a.a),d;if(".."==D(a.a))return d=new Mc(Rc,new I("node")),E(a.a),d;var f;if("@"==D(a.a))f=Fc,E(a.a),S(a,"Missing attribute name");else if("::"==D(a.a,1)){if(!/(?![0-9])[\w]/.test(D(a.a).charAt(0)))throw Error("Bad token: "+E(a.a));c=E(a.a);f=Qc[c]||null;if(!f)throw Error("No axis with name: "+c);E(a.a);S(a,"Missing node name")}else f=Nc;c=D(a.a);if(/(?![0-9])[\w\*]/.test(c.charAt(0)))if("("==
D(a.a,1)){if(!Bc(c))throw Error("Invalid node type: "+c);c=E(a.a);if(!Bc(c))throw Error("Invalid type name: "+c);Yc(a,"(");S(a,"Bad nodetype");e=D(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=$c(a);S(a,"Bad nodetype");Zc(a);c=new I(c,g)}else if(c=E(a.a),e=c.indexOf(":"),-1==e)c=new ec(c);else{var g=c.substring(0,e),h;if("*"==g)h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);c=c.substr(e+1);c=new ec(c,h)}else throw Error("Bad token: "+E(a.a));e=new Lc(cd(a),f.a);return d||
new Mc(f,c,e,"//"==b)}function cd(a){for(var b=[];"["==D(a.a);){E(a.a);S(a,"Missing predicate expression.");var c=Wc(a);b.push(c);S(a,"Unclosed predicate expression.");Yc(a,"]")}return b}function Xc(a){if("-"==D(a.a))return E(a.a),new Tc(Xc(a));var b=ad(a);if("|"!=D(a.a))a=b;else{for(b=[b];"|"==E(a.a);)S(a,"Missing next union location path."),b.push(ad(a));a.a.a--;a=new Uc(b)}return a};function dd(a){switch(a.nodeType){case 1:return ma(ed,a);case 9:return dd(a.documentElement);case 11:case 10:case 6:case 12:return fd;default:return a.parentNode?dd(a.parentNode):fd}}function fd(){return null}function ed(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?ed(a.parentNode,b):null};function gd(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=Xb(a);if($b(c))throw Error("Invalid XPath expression.");b?ha(b)||(b=la(b.lookupNamespaceURI,b)):b=function(){return null};var d=Wc(new Vc(c,b));if(!$b(c))throw Error("Bad token: "+E(c));this.evaluate=function(a,b){var c=d.a(new Rb(a));return new T(c,b)}}
function T(a,b){if(!b)if(a instanceof G)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof G))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof G?a.f():""+a;break;case 1:this.numberValue=a instanceof G?+a.f():+a;break;case 3:this.booleanValue=a instanceof G?0<a.m:!!a;break;case 4:case 5:case 6:case 7:var d=
mc(a);c=[];for(var e=J(d);e;e=J(d))c.push(e instanceof Ub?e.a:e);this.snapshotLength=a.m;this.invalidIteratorState=!1;break;case 8:case 9:d=lc(a);this.singleNodeValue=d instanceof Ub?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}T.ANY_TYPE=0;T.NUMBER_TYPE=1;T.STRING_TYPE=2;T.BOOLEAN_TYPE=3;T.UNORDERED_NODE_ITERATOR_TYPE=4;T.ORDERED_NODE_ITERATOR_TYPE=5;T.UNORDERED_NODE_SNAPSHOT_TYPE=6;T.ORDERED_NODE_SNAPSHOT_TYPE=7;T.ANY_UNORDERED_NODE_TYPE=8;T.FIRST_ORDERED_NODE_TYPE=9;function hd(a){this.lookupNamespaceURI=dd(a)}
function id(a,b){var c=a||p,d=c.Document&&c.Document.prototype||c.document;if(!d.evaluate||b)c.XPathResult=T,d.evaluate=function(a,b,c,d){return(new gd(a,c)).evaluate(b,d)},d.createExpression=function(a,b){return new gd(a,b)},d.createNSResolver=function(a){return new hd(a)}}ea("wgxpath.install",id);var U={};U.D=function(){var a={La:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
U.o=function(a,b,c){var d=B(a);if(!d.documentElement)return null;(x||gb)&&id(Cb(d));try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):U.D;if(x&&!ab(7))return d.evaluate.call(d,b,a,e,c,null);if(!x||9<=Number(cb)){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var l=g[h],m=l.namespaceURI;if(m&&!f[m]){var k=l.lookupPrefix(m);if(!k)var A=m.match(".*/(\\w+)/?$"),k=A?A[1]:"xhtml";f[m]=k}}var K={},na;for(na in f)K[f[na]]=na;e=function(a){return K[a]||null}}try{return d.evaluate(b,
a,e,c,null)}catch(Na){if("TypeError"===Na.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):U.D,d.evaluate(b,a,e,c,null);throw Na;}}catch(Na){if(!y||"NS_ERROR_ILLEGAL_VALUE"!=Na.name)throw new u(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Na);}};U.F=function(a,b){if(!a||1!=a.nodeType)throw new u(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
U.s=function(a,b){var c=function(){var c=U.o(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||U.F(c,a);return c};
U.u=function(a,b){var c=function(){var c=U.o(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();t(c,function(b){U.F(b,a)});return c};function jd(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}n=jd.prototype;n.clone=function(){return new jd(this.top,this.right,this.bottom,this.left)};n.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};n.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
n.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};n.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};n.scale=function(a,b){var c=ga(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function V(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}n=V.prototype;n.clone=function(){return new V(this.left,this.top,this.width,this.height)};n.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};n.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
n.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};n.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};n.scale=function(a,b){var c=ga(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function kd(a){a=a?B(a):document;return!x||9<=Number(cb)||"CSS1Compat"==z(a).a.compatMode?a.documentElement:a.body};function ld(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return C(a)?a:null}
function W(a,b){var c=wa(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=wb?"styleFloat":"cssFloat";var d;a:{d=c;var e=B(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||md(a,c);if(null===d)d=null;else if(0<=xa(Ha,c)){b:{var f=d.match(Ka);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(La))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Ga[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Ia,"#$1$1$2$2$3$3")),!Ja.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function md(a,b){var c=a.currentStyle||a.style,d=c[b];!da(d)&&ha(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?da(d)?d:null:(c=ld(a))?md(c,b):null}
function nd(a,b,c){function d(a){var b=od(a);return 0<b.height&&0<b.width?!0:C(a,"PATH")&&(0<b.height||0<b.width)?(a=W(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=W(a,"overflow")&&Ba(a.childNodes,function(a){return 3==a.nodeType||C(a)&&d(a)})}function e(a){return pd(a)==qd&&Ca(a.childNodes,function(a){return!C(a)||e(a)||!d(a)})}if(!C(a))throw Error("Argument to isShown must be of type Element");if(C(a,"BODY"))return!0;if(C(a,"OPTION")||C(a,"OPTGROUP"))return a=Lb(a,function(a){return C(a,"SELECT")}),
!!a&&nd(a,!0,c);var f=rd(a);if(f)return!!f.I&&0<f.rect.width&&0<f.rect.height&&nd(f.I,b,c);if(C(a,"INPUT")&&"hidden"==a.type.toLowerCase()||C(a,"NOSCRIPT"))return!1;f=W(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||sd(a))&&d(a)?!e(a):!1}function td(a){function b(a){if("none"==W(a,"display"))return!1;a=ld(a);return!a||b(a)}return nd(a,!1,b)}var qd="hidden";
function pd(a){function b(a){function b(a){return a==g?!0:!W(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==W(a,"position")?!1:!0}var c=W(a,"position");if("fixed"==c)return m=!0,a==g?null:g;for(a=ld(a);a&&!b(a);)a=ld(a);return a}function c(a){var b=a;if("visible"==l)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:W(b,"overflow-x"),y:W(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new zb(f)).a;
a=Bb(b);b=b.parentWindow||b.defaultView;a=x&&ab("10")&&b.pageYOffset!=a.scrollTop?new xb(a.scrollLeft,a.scrollTop):new xb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new xb(a.scrollLeft,a.scrollTop);return a}var e=ud(a),f=B(a),g=f.documentElement,h=f.body,l=W(g,"overflow"),m;for(a=b(a);a;a=b(a)){var k=c(a);if("visible"!=k.x||"visible"!=k.y){var A=od(a);if(!A.width||!A.height)return qd;var K=e.right<A.left,na=e.bottom<A.top;if(K&&"hidden"==k.x||na&&"hidden"==k.y)return qd;if(K&&
"visible"!=k.x||na&&"visible"!=k.y){K=d(a);na=e.bottom<A.top-K.y;if(e.right<A.left-K.x&&"visible"!=k.x||na&&"visible"!=k.x)return qd;e=pd(a);return e==qd?qd:"scroll"}K=e.left>=A.left+A.width;A=e.top>=A.top+A.height;if(K&&"hidden"==k.x||A&&"hidden"==k.y)return qd;if(K&&"visible"!=k.x||A&&"visible"!=k.y){if(m&&(k=d(a),e.left>=g.scrollWidth-k.x||e.right>=g.scrollHeight-k.y))return qd;e=pd(a);return e==qd?qd:"scroll"}}}return"none"}
function od(a){var b=rd(a);if(b)return b.rect;if(C(a,"HTML"))return a=B(a),a=(Cb(a)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new yb(a.clientWidth,a.clientHeight),new V(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new V(0,0,0,0)}b=new V(c.left,c.top,c.right-c.left,c.bottom-c.top);x&&a.ownerDocument.body&&(a=B(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function rd(a){var b=C(a,"MAP");if(!b&&!C(a,"AREA"))return null;var c=b?a:C(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=U.s('/descendant::*[@usemap = "#'+c.name+'"]',B(c)))&&(e=od(d),b||"default"==a.shape.toLowerCase()||(a=vd(a),b=Math.min(Math.max(a.left,0),e.width),c=Math.min(Math.max(a.top,0),e.height),e=new V(b+e.left,c+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{I:d,rect:e||new V(0,0,0,0)}}
function vd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new V(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new V(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new V(b,c,d-b,e-c)}return new V(0,0,0,0)}function ud(a){a=od(a);return new jd(a.top,a.left+a.width,a.top+a.height,a.left)}
function wd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function xd(a){var b=[];yd(a,b);a=za(b,wd);return wd(a.join("\n")).replace(/\xa0/g," ")}
function zd(a,b,c){if(C(a,"BR"))b.push("");else{var d=C(a,"TD"),e=W(a,"display"),f=!d&&!(0<=xa(Ad,e)),g=da(a.previousElementSibling)?a.previousElementSibling:Db(a.previousSibling),g=g?W(g,"display"):"",h=W(a,"float")||W(a,"cssFloat")||W(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var l=td(a),m=null,k=null;l&&(m=W(a,"white-space"),k=W(a,"text-transform"));t(a.childNodes,function(a){c(a,b,l,m,k)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||sa(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function yd(a,b){zd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?Bd(a,b,f,g):C(a)&&yd(a,b)})}var Ad="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Bd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";sa(c," ")&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function sd(a){if(wb){if("relative"==W(a,"position"))return 1;a=W(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return Cd(a)}function Cd(a){var b=1,c=W(a,"opacity");c&&(b=Number(c));(a=ld(a))&&(b*=Cd(a));return b};var Dd=!(x&&!ob(10)),Ed=gb?!qb(4):!sb,Fd=x&&pa.navigator.msPointerEnabled;function X(a,b,c){this.g=a;this.a=b;this.b=c}X.prototype.create=function(a){a=B(a);wb&&a.createEventObject?a=a.createEventObject():(a=a.createEvent("HTMLEvents"),a.initEvent(this.g,this.a,this.b));return a};X.prototype.toString=function(){return this.g};function Y(a,b,c){X.call(this,a,b,c)}r(Y,X);
Y.prototype.create=function(a,b){if(!y&&this==Gd)throw new u(9,"Browser does not support a mouse pixel scroll event.");var c=B(a),d;if(wb){d=c.createEventObject();d.altKey=b.altKey;d.ctrlKey=b.ctrlKey;d.metaKey=b.metaKey;d.shiftKey=b.shiftKey;d.button=b.button;d.clientX=b.clientX;d.clientY=b.clientY;c=function(a,b){Object.defineProperty(d,a,{get:function(){return b}})};if(this==Hd||this==Id)if(Object.defineProperty){var e=this==Hd;c("fromElement",e?a:b.relatedTarget);c("toElement",e?b.relatedTarget:
a)}else d.relatedTarget=b.relatedTarget;this==Jd&&(Object.defineProperty?c("wheelDelta",b.wheelDelta):d.detail=b.wheelDelta)}else{e=Cb(c);d=c.createEvent("MouseEvents");var f=1;this==Jd&&(y||(d.wheelDelta=b.wheelDelta),y&&(f=b.wheelDelta/-40));y&&this==Gd&&(f=b.wheelDelta);d.initMouseEvent(this.g,this.a,this.b,e,f,b.clientX,b.clientY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);if(x&&!d.pageX&&!d.pageY&&Object.defineProperty){var e=Bb(z(a).a),c=kd(c),g=b.clientX+
e.scrollLeft-c.clientLeft,h=b.clientY+e.scrollTop-c.clientTop;Object.defineProperty(d,"pageX",{get:function(){return g}});Object.defineProperty(d,"pageY",{get:function(){return h}})}}return d};function Kd(a,b,c){X.call(this,a,b,c)}r(Kd,X);
Kd.prototype.create=function(a,b){var c=B(a);if(y){var d=Cb(c),e=b.charCode?0:b.keyCode,c=c.createEvent("KeyboardEvent");c.initKeyEvent(this.g,this.a,this.b,d,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,e,b.charCode);this.g==Ld&&b.preventDefault&&c.preventDefault()}else if(wb?c=c.createEventObject():(c=c.createEvent("Events"),c.initEvent(this.g,this.a,this.b)),c.altKey=b.altKey,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.keyCode=b.charCode||b.keyCode,Wa||Va)c.charCode=this==Ld?c.keyCode:
0;return c};function Md(a,b,c){X.call(this,a,b,c)}r(Md,X);
Md.prototype.create=function(a,b){function c(b){b=za(b,function(b){return f.createTouch(g,a,b.identifier,b.pageX,b.pageY,b.screenX,b.screenY)});return f.createTouchList.apply(f,b)}function d(b){var c=za(b,function(b){return{identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a}});c.item=function(a){return c[a]};return c}function e(a){return Ed?d(a):c(a)}if(!Dd)throw new u(9,"Browser does not support firing touch events.");
var f=B(a),g=Cb(f),h=e(b.changedTouches),l=b.touches==b.changedTouches?h:e(b.touches),m=b.targetTouches==b.changedTouches?h:e(b.targetTouches),k;Ed?(k=f.createEvent("MouseEvents"),k.initMouseEvent(this.g,this.a,this.b,g,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,b.relatedTarget),k.touches=l,k.targetTouches=m,k.changedTouches=h,k.scale=b.scale,k.rotation=b.rotation):(k=f.createEvent("TouchEvent"),0==k.initTouchEvent.length?k.initTouchEvent(l,m,h,this.g,g,0,0,b.clientX,b.clientY,
b.ctrlKey,b.altKey,b.shiftKey,b.metaKey):k.initTouchEvent(this.g,this.a,this.b,g,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,l,m,h,b.scale,b.rotation),k.relatedTarget=b.relatedTarget);return k};function Nd(a,b,c){X.call(this,a,b,c)}r(Nd,X);
Nd.prototype.create=function(a,b){if(!Fd)throw new u(9,"Browser does not support MSGesture events.");var c=B(a),d=Cb(c),c=c.createEvent("MSGestureEvent");c.initGestureEvent(this.g,this.a,this.b,d,1,0,0,b.clientX,b.clientY,0,0,b.translationX,b.translationY,b.scale,b.expansion,b.rotation,b.velocityX,b.velocityY,b.velocityExpansion,b.velocityAngular,(new Date).getTime(),b.relatedTarget);return c};function Od(a,b,c){X.call(this,a,b,c)}r(Od,X);
Od.prototype.create=function(a,b){if(!Fd)throw new u(9,"Browser does not support MSPointer events.");var c=B(a),d=Cb(c),c=c.createEvent("MSPointerEvent");c.initPointerEvent(this.g,this.a,this.b,d,0,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget,0,0,b.width,b.height,b.pressure,b.rotation,b.tiltX,b.tiltY,b.pointerId,b.pointerType,0,b.isPrimary);return c};
var Hd=new Y("mouseout",!0,!0),Id=new Y("mouseover",!0,!0),Jd=new Y(y?"DOMMouseScroll":"mousewheel",!0,!0),Gd=new Y("MozMousePixelScroll",!0,!0),Ld=new Kd("keypress",!0,!0),Pd={f:new X("blur",!1,!1),c:new X("change",!0,!1),Ma:new X("focus",!1,!1),$:new X("focusin",!0,!1),aa:new X("focusout",!0,!1),ba:new X("input",!0,!1),Ba:new X("orientationchange",!1,!1),Ca:new X("propertychange",!1,!1),Da:new X("select",!0,!1),Ea:new X("submit",!0,!0),Fa:new X("textInput",!0,!0),i:new Y("click",!0,!0),v:new Y("contextmenu",
!0,!0),B:new Y("dblclick",!0,!0),fa:new Y("mousedown",!0,!0),ga:new Y("mousemove",!0,!1),ia:Hd,ja:Id,la:new Y("mouseup",!0,!0),ma:Jd,ka:Gd,ca:new Kd("keydown",!0,!0),da:Ld,ea:new Kd("keyup",!0,!0),Ga:new Md("touchend",!0,!0),Ha:new Md("touchmove",!0,!0),Ia:new Md("touchstart",!0,!0),na:new Nd("MSGestureChange",!0,!0),oa:new Nd("MSGestureEnd",!0,!0),pa:new Nd("MSGestureHold",!0,!0),qa:new Nd("MSGestureStart",!0,!0),ra:new Nd("MSGestureTap",!0,!0),ta:new Nd("MSInertiaStart",!0,!0),sa:new Od("MSGotPointerCapture",
!0,!1),ua:new Od("MSLostPointerCapture",!0,!1),va:new Od("MSPointerCancel",!0,!0),wa:new Od("MSPointerDown",!0,!0),xa:new Od("MSPointerMove",!0,!0),ya:new Od("MSPointerOver",!0,!0),Z:new Od("MSPointerOut",!0,!0),za:new Od("MSPointerUp",!0,!0)};function Qd(a){qa.call(this,a)}r(Qd,qa);Wa||y&&ob(3.5)||x&&ob(8);var Rd={A:function(a){return!(!a.querySelectorAll||!a.querySelector)},s:function(a,b){if(!a)throw new u(32,"No class name specified");a=ta(a);if(-1!==a.indexOf(" "))throw new u(32,"Compound class names not permitted");if(Rd.A(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(d){throw new u(32,"An invalid or illegal class name was specified");}var c=Mb(z(b),"*",a,b);return c.length?c[0]:null},u:function(a,b){if(!a)throw new u(32,"No class name specified");a=ta(a);if(-1!==a.indexOf(" "))throw new u(32,
"Compound class names not permitted");if(Rd.A(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new u(32,"An invalid or illegal class name was specified");}return Mb(z(b),"*",a,b)}};var Sd={s:function(a,b){if(!ha(b.querySelector)&&x&&ob(8)&&!ia(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ta(a);var c;try{c=b.querySelector(a)}catch(d){throw new u(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},u:function(a,b){if(!ha(b.querySelectorAll)&&x&&ob(8)&&!ia(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ta(a);try{return b.querySelectorAll(a)}catch(c){throw new u(32,
"An invalid or illegal selector was specified");}}};var Td={A:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},s:function(a,b){var c=z(b),d=q(a)?c.a.getElementById(a):a;return d?Nb(d,"id")==a&&Eb(b,d)?d:Da(Mb(c,"*"),function(c){return Nb(c,"id")==a&&Eb(b,c)}):null},u:function(a,b){if(!a)return[];if(Td.A(b,a))try{return b.querySelectorAll("#"+Td.S(a))}catch(d){return[]}var c=Mb(z(b),"*",null,b);return ya(c,function(b){return Nb(b,"id")==a})},S:function(a){return a.replace(/(['"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var Ud={},Vd={};Ud.N=function(a,b,c){var d;try{d=Sd.u("a",b)}catch(e){d=Mb(z(b),"A",null,b)}return Da(d,function(b){b=xd(b);return c&&-1!=b.indexOf(a)||b==a})};Ud.J=function(a,b,c){var d;try{d=Sd.u("a",b)}catch(e){d=Mb(z(b),"A",null,b)}return ya(d,function(b){b=xd(b);return c&&-1!=b.indexOf(a)||b==a})};Ud.s=function(a,b){return Ud.N(a,b,!1)};Ud.u=function(a,b){return Ud.J(a,b,!1)};Vd.s=function(a,b){return Ud.N(a,b,!0)};Vd.u=function(a,b){return Ud.J(a,b,!0)};var Wd={s:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},u:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var Xd={className:Rd,"class name":Rd,css:Sd,"css selector":Sd,id:Td,linkText:Ud,"link text":Ud,name:{s:function(a,b){var c=Mb(z(b),"*",null,b);return Da(c,function(b){return Nb(b,"name")==a})},u:function(a,b){var c=Mb(z(b),"*",null,b);return ya(c,function(b){return Nb(b,"name")==a})}},partialLinkText:Vd,"partial link text":Vd,tagName:Wd,"tag name":Wd,xpath:U};
function Yd(a,b){var c;a:{for(c in a)if(a.hasOwnProperty(c))break a;c=null}if(c){var d=Xd[c];if(d&&ha(d.s))return d.s(a[c],b||pa.document)}throw Error("Unsupported locator strategy: "+c);};var Zd={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Qd("Illegal Index: "+a);if(b.length<=c)throw new Qd("Index out of range: "+a);return[b[c]]},name:function(a,b){return ya(b,function(b){return Qb(b,"name")==a})},value:function(a,b){return ya(b,function(b){return Qb(b,"value")===a})}};function $d(a,b){return(new RegExp(a)).test(b)}function ae(a,b){return(new RegExp(a,"i")).test(b)}function be(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var ce={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+be(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(be(a))).test(b)},regex:$d,regexi:ae,regexpi:ae,regexp:$d};function de(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";var c;if(3==a.nodeType)return c=a.data,b||(c=c.replace(/\n|\r|\t/g," ")),c.replace(/&nbsp/," ");if(1==a.nodeType&&"SCRIPT"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);f&&(c+=de(f,d))}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");lb.ha&&qb(9)&&(c=c.replace(/&#100;/," "));return c}return""}
;var Z={U:function(a,b){return a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?Z.H(a,b):Z.G(a,b):Z.O(a,b)},P:function(a,b){return ee(b||B(pa),function(b){return b.alt==a})},R:function(a,b){return ee(b||B(pa),function(b){return b.className==a})},G:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},T:function(a,b){return Yd({id:a},b)},H:function(a,b){return Z.id(a,b)||Z.name(a,b)},j:function(a,b){var c=b||B(pa);z(c);var d;d=Ab(document,"*",null,c);c=a.split(" ");for(c[0]="name="+
c[0];c.length;){var e=c.shift(),f=d;d="value";var g=e.match(/^([A-Za-z]+)=(.+)/);g&&(d=g[1].toLowerCase(),e=g[2]);g=Zd[d];if(!g)throw new Qd("Unrecognised element-filter type: '"+d+"'");d=g(e,f)}return 0<d.length?d[0]:null},W:function(a,b){try{var c;a:{var d=a,d=decodeURIComponent(d),e=b||document,f,g=e||document,h=g.$wdc_;h||(h=g.$wdc_={},h.K=oa());h.K||(h.K=oa());f=h;if(!(f&&d in f))throw new u(10,"Element does not exist in cache");var l=f[d];if(l&&"setInterval"in l){if(l.closed)throw delete f[d],
new u(23,"Window has been closed.");c=l}else{for(g=l;g;){if(g==e.documentElement){c=l;break a}g=g.parentNode}delete f[d];throw new u(10,"Element is no longer attached to the DOM");}}return c}catch(m){return null}},O:function(a,b){var c=sa(a,"/"),d={xpath:a};try{var e=Yd(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Yd(d,b)}};Z.alt=Z.P;Z["class"]=Z.R;Z.dom=Z.G;Z.id=Z.T;Z.identifier=Z.H;Z.implicit=Z.U;
Z.link=function(a,b){for(var c=(b||B(pa)).getElementsByTagName("a"),d=0;d<c.length;d++){var e=c[d],f=e,g="";y&&"1.8"<=Za||Wa||x?g=de(f,!1):f.textContent?g=f.textContent:f.innerText&&(g=f.innerText);f=g=g.replace(/\r\n|\r/g,"\n");f=f.replace(/\ +/g," ");g=new RegExp(String.fromCharCode(160),"g");if(Wa)for(g=String.fromCharCode(160);-1!=f.indexOf(g);)f=f.replace(g," ");else f=f.replace(g," ");var g=f,f=ta(g),h=a,g="glob",l=/^([a-zA-Z-]+):(.*)/.exec(h);if(l){var m=l[1],l=l[2];ce[m.toLowerCase()]&&(g=
m.toLowerCase(),h=l)}m=ce[g];if(!m)throw new Qd("Cannot find pattern matching strategy: "+g);"glob"==g?(h.indexOf("glob:")||(h=h.substring(5)),m=ce.glob):"exact"!=g||h.indexOf("exact:")||(h=h.substring(6));h=ma(m,h);h.Ja=g;if(h(f))return e}return null};Z.name=Z.j;Z.stored=Z.W;Z.xpath=Z.O;function fe(a,b,c,d){var e=Z[a];if(!e)throw new Qd("Unrecognised locator type: '"+a+"'");if(c=e.call(null,b,c))return c;if(!d)return null;for(e=0;e<d.frames.length;e++){var f;try{f=d.frames[e].document}catch(g){}if(f&&(c=fe(a,b,f,d.frames[e])))return c}return null}function ee(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType&&(b(e)||(e=ee(e,b))))return e}return null};function ge(a){var b="";a&&(b=a.toUpperCase());return(b=Pd[b])?b:{create:function(b){b=B(b);wb&&b.createEventObject?b=b.createEventObject():(b=b.createEvent("HTMLEvents"),b.initEvent(a,!0,!0));return b},g:a}};ea("_",function(a,b){var c;if(q(a)){var d;(d=a.match(/^([A-Za-z]+)=.+/))?(d=d[1].toLowerCase(),d={type:d,string:a.substring(d.length+1)}):(d={string:"",type:""},d.string=a,d.type=a.lastIndexOf("//",0)?a.lastIndexOf("document.",0)?"identifier":"dom":"xpath");c=pa||pa;d=fe(d.type,d.string,c.document,c);if(!d)throw new Qd("Element "+a+" not found");c=d}else c=a;d=ge(b);if(!d)throw Error("Unable to find type for: "+b);var e=d.create(c,void 0);"isTrusted"in e||(e.isTrusted=!1);wb&&c.fireEvent?c.fireEvent("on"+
d.g,e):c.dispatchEvent(e)});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
